name: Save Data

on:
  repository_dispatch:
    types: [save-data]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Save to Gist
        env:
          GIST_TOKEN: 11CAGKWPI0gLlnT8kymoba_hU45w3a3EfqS37sQZg6ue6CO6AsXrvNV2lXCG4LmjwCWUR66D4IYEGcCa6w
          GIST_ID: 3fbfbda72d77e086968b28c20c423e0d
          PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "$PAYLOAD" > /tmp/data.json
          curl -s -X PATCH \
            -H "Authorization: token $GIST_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "{\"files\":{\"solubio.json\":{\"content\":$(jq -Rs . /tmp/data.json)}}}" \
            "https://api.github.com/gists/$GIST_ID"
